
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/practice?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: secured
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  servlet:
    context-path: /practice
  port: 9099

springdoc:
  api-docs:
    groups:
      enabled: true